fix: update webpack config
onecx/onecx-tenant-ui pull request #21
Opened 2024-05-02 09:25 UTC by KimFFVII

2024-05-02 10:57 UTC, SchettlerKoehler requested changes

2024-05-02 10:57 UTC, SchettlerKoehler commented on package.json
> -    "@onecx/nx-plugin": "1.2.0",
This has to stay

2024-05-02 11:10 UTC, SchettlerKoehler approved these changes

2024-05-03 06:39 UTC, HenryT-CG approved these changes

2024-05-03 06:39 UTC, merged